site:
  title: D瓜哥 -- 代码笔记
  url: https://blog.diguage.com
  start_page: mysql::index.adoc
content:
  sources:
  - url: https://github.com/diguage/networking-protocols-notes.git
    branches: master
  - url: https://github.com/diguage/martes.git
    branches: master
  - url: https://github.com/diguage/mysql-notes.git
    branches: master
  - url: https://github.com/diguage/blog.git
    branches: master
  - url: https://github.com/diguage/tour-plan.git
    branches: master
  - url: https://github.com/diguage/docker-notes.git
    branches: master
asciidoc:
  # extensions:
  #   - asciidoctor-plantuml
  attributes:
    source-highlighter: coderay
    icons: font
    stem: 'latexmath'
    source_attrs: 'linenums'
    source_base_path: 'https://raw.githubusercontent.com/diguage/leetcode/master/src/main/java/com/diguage/algorithm/leetcode'
ui:
  bundle:
    url: https://github.com/diguage/antora-ui-default/releases/download/1.4.1/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: public
