site:
  title: D瓜哥の博客
  url: https://blog.diguage.com
  start_page: network::index.adoc
content:
  sources:
  - url: https://github.com/diguage/networking-protocols-notes.git
    branches: master
  - url: https://github.com/diguage/martes.git
    branches: master
  - url: https://github.com/diguage/mysql-notes.git
    branches: master
asciidoc:
  attributes:
    icons: font
    stem: 'latexmath'
    source_attrs: 'linenums'
    source_base_path: 'https://raw.githubusercontent.com/diguage/leetcode/master/src/main/java/com/diguage/algorithm/leetcode'
ui:
  bundle:
    url: https://github.com/diguage/antora-ui-default/releases/download/v1.0.0/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: public
